#!/bin/sh

# Directory aliases
homework='/home/fernando/wstorage/Documentos/Estudios/5to semestre'
playlist='/home/fernando/wstorage/multimedia/tidal/download/Playlist/'
memes='/home/fernando/wstorage/multimedia/memes'
notes='/home/fernando/wstorage/Documentos/notes'
multimedia='/home/fernando/wstorage/multimedia'

alias wall='sxiv -bt ~/.local/share/wallhaven'
alias n='vi ~/wstorage/Documentos/notes/index.md'
